/*
 * userApp.c
 *
 *  Created on: Created on: Oct 29, 2025
 *      Author: Niall.OKeeffe@atu.ie
 */

#include "main.h"
#include "userApp.h"
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "queue.h"
#include <string.h>
#include "event_groups.h"
#include "stdlib.h"
#include "timers.h"

//Peripheral Handles
extern UART_HandleTypeDef huart1;
extern TIM_HandleTypeDef htim6;


//Network variables
extern int network_wr(Network* n, unsigned char* buffer, int len, int timeout_ms);
extern int network_rd(Network* n, unsigned char* buffer, int len, int timeout_ms);
extern int net_if_init(void * if_ctxt);
extern int net_if_deinit(void * if_ctxt);
extern int net_if_reinit(void * if_ctxt);
extern int wifi_net_if_init(void * if_ctxt);

//RTOS task function prototypes and object declarations

QueueHandle_t dataQueue = NULL;
EventGroupHandle_t Publish_EventGroup = NULL;
EventGroupHandle_t Button_EventGroup = NULL;
static void initTask(void * pvParameters);
static void temperatureTask(void * pvParameters);
static void humidityTask(void * pvParameters);
static void pressureTask(void * pvParameters);
static void accelerometerTask(void * pvParameters);
static void RTC_Task(void * pvParameters);
static void displayTask(void * pvParameters);
//static void publishTask(void * pvParameters);
TimerHandle_t autoReloadTimer = NULL;
TimerHandle_t ledTimer = NULL;
TaskHandle_t accTaskHandle = NULL;
static void autoReloadTimerCallback (TimerHandle_t xTimer);
static void ledTimerCallback (TimerHandle_t ledTimer);
SemaphoreHandle_t publishSemaphore = NULL, oneSecondSemaphore = NULL, pressureSemaphore = NULL, timerSemaphore = NULL;
#define buttonBit (1<<5)
#define unblockBit (1<<6)
#define tempBit (1<<3)
#define humBit (1<<4)
uint8_t ch;

typedef struct {
	uint8_t ID;
	uint32_t dataField;
} dataStruct_t;

#define temperatureID 1
#define humidityID 2
#define pressureID 3
#define accelerometerID 4
#define buttonID 5

uint8_t RTC_TaskRunning = 0;

uint8_t timeDisplay = 0, readSensor = 0;
net_hnd_t hnet;
Network network;
MQTTPacket_connectData options = MQTTPacket_connectData_initializer;
net_sockhnd_t socket;
MQTTClient client;




typedef struct {
  char *HostName;
  char *HostPort;
  char *ConnSecurity;
  char *MQClientId;
  char *MQUserName;
  char *MQUserPwd;
#ifdef LITMUS_LOOP
  char *LoopTopicId;
#endif
} device_config_t;


/*--------------------------------------------------------------------
 * EXTI interrupt handler callback function
 * Will give a semaphore when the user button is pressed
 --------------------------------------------------------------------*/
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
	BaseType_t xHigherPriorityTaskWoken;
	switch (GPIO_Pin)
	{
	case (GPIO_PIN_1):	//IRQ generated by WiFi module
		{
		SPI_WIFI_ISR();
		break;
		}

	case (BUTTON_EXTI13_Pin) :	//IRQ generated by user button
		{
			dataStruct_t uartStruct;
			uint8_t buttonState = 0;   // 0 = OFF, 1 = ON
			char button[25];
			static uint32_t lastTick = 0;
			uint32_t now = xTaskGetTickCountFromISR();

			// 20ms debounce (MANDATORY for EXTI13)
			if ((now - lastTick) < pdMS_TO_TICKS(20)){
			    break;
			}

			lastTick = now;


			EventBits_t bits = xEventGroupGetBitsFromISR(Button_EventGroup);
			if (bits & buttonBit){

			   xEventGroupClearBitsFromISR(Button_EventGroup, buttonBit);
			   HAL_TIM_Base_Stop_IT(&htim6);

			   buttonState = 1;
			   uartStruct.ID = buttonID;
			   uartStruct.dataField = buttonState;

			   xHigherPriorityTaskWoken = pdFALSE;
			   xQueueSendFromISR(dataQueue, &uartStruct, &xHigherPriorityTaskWoken);
			   portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
			   //printf("DISPLAY PAUSED\r\n");
			   }
			else{
				// BLOCKED, RESUME display task
				buttonState = 0;
				uartStruct.ID = buttonID;
				uartStruct.dataField = buttonState;
				xHigherPriorityTaskWoken = pdFALSE;
				xQueueSendFromISR(dataQueue, &uartStruct, &xHigherPriorityTaskWoken);
				portYIELD_FROM_ISR(xHigherPriorityTaskWoken);

			    xEventGroupSetBitsFromISR(Button_EventGroup, buttonBit, &xHigherPriorityTaskWoken);
			    portYIELD_FROM_ISR(xHigherPriorityTaskWoken);

			    HAL_TIM_Base_Start_IT(&htim6);

			    //printf("DISPLAY RESUMED\r\n");
			   }

		}

	default:
	{
		break;
	}
	}
}

void HAL_UART_RxCpltCallback (UART_HandleTypeDef * huart){
	BaseType_t xHigherPriorityTaskWoken = pdFALSE;
	if(huart->Instance == USART1){
		switch(ch){
		case 't':

			xEventGroupSetBitsFromISR(Publish_EventGroup, tempBit, &xHigherPriorityTaskWoken);
			portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
			printf("\nCharacter t received, sending temperature to queue\r\n");
			break;

		case 'h':

			xEventGroupSetBitsFromISR(Publish_EventGroup, humBit, &xHigherPriorityTaskWoken);
			portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
			printf("\nCharacter h received, sending humidity to queue\r\n");
			break;

		default:
			break;
		}

		HAL_UART_Receive_IT(&huart1, &ch, 1);
	}
}


void TIM6_Handler() {
	BaseType_t xHigherPriorityTaskWoken = pdFALSE;
	xSemaphoreGiveFromISR(timerSemaphore, &xHigherPriorityTaskWoken);
	portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
}

/*--------------------------------------------------------------------
 * RTC timer event interrupt handler callback function
 * Runs every second and gives a semaphore if the RTC task is running
 --------------------------------------------------------------------*/
void HAL_RTCEx_WakeUpTimerEventCallback (RTC_HandleTypeDef * hrtc) {
	BaseType_t xHigherPriorityTaskWoken = pdFALSE;
	if(RTC_TaskRunning){
		xHigherPriorityTaskWoken = pdFALSE;
		xSemaphoreGiveFromISR(oneSecondSemaphore, &xHigherPriorityTaskWoken);
		portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
	}
}

/*--------------------------------------------------------------------------
 * Subscribe message callback function
 * Called every time a publish meassage is received from a subscribed topic
 --------------------------------------------------------------------------*/
void subscribeMessageHandler(MessageData* data)
{
	static char mqtt_msg[MQTT_MSG_BUFFER_SIZE], mqtt_topic[MQTT_TOPIC_BUFFER_SIZE];
	snprintf(mqtt_msg, data->message->payloadlen+1, "%s", (char *)data->message->payload);
	snprintf(mqtt_topic, data->topicName->lenstring.len+1, "%s", data->topicName->lenstring.data);
	printf("\r\nPublished message from MQTT broker\r\n");
	printf("Topic: %s, Payload: %s\r\n\n", mqtt_topic, mqtt_msg);

	//Change the string parsing to match your Ubidots settings
	if(strstr(mqtt_topic, "rtosproject/ledonoff")) {	//check topic (variable)
		if(strstr(mqtt_msg, "\"value\": 1.0")) { //check data published from topic (variable)
			xTimerStart(autoReloadTimer, 0);
			printf("timer start\r\n\n");
			printf("Accelerometer On...\r\n");

		}
		else {
			xTimerStop(autoReloadTimer, 0);
			printf("timer stop\r\n\n");
			printf("Accelerometer Off...\r\n");
		}

	}

	if(strstr(mqtt_topic, "rtosproject/ledslider")) {	//check topic (variable)

		if(strstr(mqtt_msg, "\"value\": 0.0")) { //check data published from topic (variable)
			printf("LED OFF..\r\n\n");
			xTimerStop(ledTimer, 0);
			HAL_GPIO_WritePin(LED2_GPIO_Port, LED2_Pin, 0);
		}
		if(strstr(mqtt_msg, "\"value\": 200.0")) { //check data published from topic (variable)
			printf("LED at 200Hz\r\n\n");
			xTimerStart(ledTimer, 0);
			xTimerChangePeriod(ledTimer, pdMS_TO_TICKS(200), 0);
		}
		if(strstr(mqtt_msg, "\"value\": 400.0")) { //check data published from topic (variable)
			printf("LED at 400Hz\r\n\n");
			xTimerStart(ledTimer, 0);
			xTimerChangePeriod(ledTimer, pdMS_TO_TICKS(400), 0);
		}
		if(strstr(mqtt_msg, "\"value\": 600.0")) { //check data published from topic (variable)
			printf("LED at 600Hz\r\n\n");
			xTimerStart(ledTimer, 0);
			xTimerChangePeriod(ledTimer, pdMS_TO_TICKS(600), 0);
		}
		if(strstr(mqtt_msg, "\"value\": 800.0")) { //check data published from topic (variable)
			printf("LED at 800Hz\r\n\n");
			xTimerStart(ledTimer, 0);
			xTimerChangePeriod(ledTimer, pdMS_TO_TICKS(800), 0);
		}
		if(strstr(mqtt_msg, "\"value\": 1000.0")) { //check data published from topic (variable)
			printf("LED at 1000Hz\r\n\n");
			xTimerStart(ledTimer, 0);
			xTimerChangePeriod(ledTimer, pdMS_TO_TICKS(1000), 0);
		}

	}




}

static void temperatureTask(void * pvParameters) {
	EventBits_t PubTemp_Bits;
	dataStruct_t uartStruct;

	printf("\nStarting Temperature Task\r\n");
	BSP_TSENSOR_Init();		//Initialise temperature sensor
	while(1) {
		PubTemp_Bits = xEventGroupWaitBits(Publish_EventGroup, tempBit, pdTRUE, pdTRUE, portMAX_DELAY);

		printf("Event Bit set, Publishing Temp\r\n\n");
		float tempF = BSP_TSENSOR_ReadTemp();
		uint16_t tempI = tempF*10;
		uartStruct.ID = temperatureID;
		uartStruct.dataField = tempI;

		xQueueSend(dataQueue, &uartStruct, 0);

		vTaskDelay(pdMS_TO_TICKS(100));
	}
}

static void humidityTask(void * pvParameters) {
	EventBits_t PubHum_Bits;
	dataStruct_t uartStruct;

	printf("\nStarting Humidity Task\r\n");
	BSP_HSENSOR_Init();		//Initialise humidity sensor
	while(1) {
		PubHum_Bits = xEventGroupWaitBits(Publish_EventGroup, humBit, pdTRUE, pdTRUE, portMAX_DELAY);

		printf("\nEvent Bit set, Publishing Humidity\r\n\n");
		float humF = BSP_HSENSOR_ReadHumidity();
		uint16_t humI = humF*10;
		uartStruct.ID = humidityID;
		uartStruct.dataField = humI;

		xQueueSend(dataQueue, &uartStruct, 0);

		vTaskDelay(pdMS_TO_TICKS(100));
	}
}

static void pressureTask(void * pvParameters) {
	dataStruct_t uartStruct;
	printf("\nStarting Pressure Task\r\n");
	BSP_PSENSOR_Init();		//Initialise pressure sensor

	while(1) {
		if(xSemaphoreTake(timerSemaphore, 0) == pdTRUE) {
			float pressF = BSP_PSENSOR_ReadPressure();
			uint16_t pressI = pressF*10;

			uartStruct.ID = pressureID;
			uartStruct.dataField = pressI;

			xQueueSend(dataQueue, &uartStruct, 0);

			vTaskDelay(pdMS_TO_TICKS(100));

		}
		vTaskDelay(pdMS_TO_TICKS(100));
	}
}

static void accelerometerTask(void * pvParameters) {
	uint32_t TNV;
	int16_t accelXYZ[3];   // X, Y, Z value
	dataStruct_t uartStruct;
	float tiltAngle;
	BSP_ACCELERO_Init();
	printf("\nStarting Accelerometer Task\r\n");
	while(1) {

		TNV = ulTaskNotifyTake(pdTRUE, 0);
		if(TNV){


			BSP_ACCELERO_AccGetXYZ(accelXYZ);
			tiltAngle = accelXYZ[0];

			uartStruct.ID = accelerometerID;
			uartStruct.dataField = tiltAngle;

			xQueueSend(dataQueue, &uartStruct, 0);

			vTaskDelay(pdMS_TO_TICKS(100));
		}
	}
	vTaskDelay(pdMS_TO_TICKS(100));
}

static void autoReloadTimerCallback(TimerHandle_t xTimer) {
	//task notification sent to Accelerometer Task
	xTaskNotifyGive(accTaskHandle);

}

static void ledTimerCallback(TimerHandle_t ledTimer) {
	HAL_GPIO_TogglePin(LED2_GPIO_Port, LED2_Pin);

}


/*-----------------------------------------------------------
 * Task to print the date and time when a semaphore is taken
-------------------------------------------------------------*/
static void RTC_Task(void * pvParameters) {
	RTC_TimeTypeDef sTime;
	RTC_DateTypeDef sDate;
	char timeBuffer[40];

	RTC_TaskRunning = 1;	//flag set to allow RTC event interrupt handler callback to send semaphores

	while(1) {
		MQTTYield(&client, 200);	//Yield needed to allow check for received published messages from subscribed topics

		if(xSemaphoreTake(oneSecondSemaphore, 0) == pdTRUE) {
			timeDisplay = 0;
			HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
			HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN);
			sprintf(timeBuffer, "%02d/%02d/%02d %02d:%02d:%02d\r\n", sDate.Date, sDate.Month, sDate.Year, sTime.Hours+1, sTime.Minutes, sTime.Seconds);
			printf("%s", timeBuffer);
		}
		vTaskDelay(pdMS_TO_TICKS(100));
	}
}

void displayTask(void * pvParameters) {
	printf("Starting display task\r\n\n");
	EventBits_t Block_Bits;
	dataStruct_t rxStruct;
	MQTTMessage mqmsg;
	char temperature[25];
	char humidity[25];
	char pressure[25];
	char button[25];
	char accelerometer[25];
	uint32_t setTemp  = 0;
	uint32_t setHum  = 0;
	uint32_t setPress  = 0;
	uint32_t setACC = 0;
	uint32_t setState = 0;

	while(1) {
			Block_Bits = xEventGroupWaitBits(Button_EventGroup, buttonBit, pdFALSE, pdTRUE, portMAX_DELAY);

			if(xQueueReceive(dataQueue, &rxStruct, portMAX_DELAY) == pdTRUE){
				//print data
				printf("\nData received from queue\r\n");
				switch(rxStruct.ID) {
					case buttonID:
						setState = rxStruct.dataField;
						sprintf(button, "{\"button_state\":%d}", setState);
						printf("Publishing Button State: %d\r\n", setState);

						memset(&mqmsg, 0, sizeof(MQTTMessage));
						mqmsg.qos = QOS0;
						mqmsg.payload = (char *) button;
						mqmsg.payloadlen = strlen(button);

						//change the device api label to match your Ubidots configuration
						MQTTPublish(&client, "/v1.6/devices/rtosproject", &mqmsg);
						break;

					case temperatureID:
						setTemp = rxStruct.dataField;
						printf("\nTemperature Received \r\n");
						//change string to match your variable api label
						sprintf(temperature, "{\"t1\":%d.%d}", setTemp/10, setTemp%10);
						printf("Publishing Temperature: %sC\r\n", temperature);
						memset(&mqmsg, 0, sizeof(MQTTMessage));
						mqmsg.qos = QOS0;
						mqmsg.payload = (char *) temperature;
						mqmsg.payloadlen = strlen(temperature);

						//change the device api label to match your Ubidots configuration
						MQTTPublish(&client, "/v1.6/devices/rtosproject", &mqmsg);

						vTaskDelay(pdMS_TO_TICKS(100));
						break;

					case humidityID:
						setHum = rxStruct.dataField;
						printf("\nHumidity Received\r\n");
						//change string to match your variable api label
						sprintf(humidity, "{\"h1\":%d.%d}", setHum/10, setHum%10);
						printf("Publishing Humidity: %s%\r\n", humidity);
						memset(&mqmsg, 0, sizeof(MQTTMessage));
						mqmsg.qos = QOS0;
						mqmsg.payload = (char *) humidity;
						mqmsg.payloadlen = strlen(humidity);

						//change the device api label to match your Ubidots configuration
						MQTTPublish(&client, "/v1.6/devices/rtosproject", &mqmsg);

						vTaskDelay(pdMS_TO_TICKS(100));
						break;

					case pressureID:
						setPress = rxStruct.dataField;
						printf("\nPressure Received\r\n");
						//change string to match your variable api label
						sprintf(pressure, "{\"p1\":%d.%d}", setPress/10, setPress%10);
						printf("Publishing Pressure: %sBar\r\n", pressure);
						memset(&mqmsg, 0, sizeof(MQTTMessage));
						mqmsg.qos = QOS0;
						mqmsg.payload = (char *) pressure;
						mqmsg.payloadlen = strlen(pressure);

						//change the device api label to match your Ubidots configuration
						MQTTPublish(&client, "/v1.6/devices/rtosproject", &mqmsg);

						vTaskDelay(pdMS_TO_TICKS(100));
						break;

					case accelerometerID:
						setACC = rxStruct.dataField;
						printf("\nAccelerometer Reading Received\r\n");
						//change string to match your variable api label
						sprintf(accelerometer, "{\"a1\":%d.%d}", setACC/10, setACC%10);
						printf("Publishing Accelerometer Tilt: %s degrees\r\n", accelerometer);
						memset(&mqmsg, 0, sizeof(MQTTMessage));
						mqmsg.qos = QOS0;
						mqmsg.payload = (char *) accelerometer;
						mqmsg.payloadlen = strlen(accelerometer);

						//change the device api label to match your Ubidots configuration
						MQTTPublish(&client, "/v1.6/devices/rtosproject", &mqmsg);

						vTaskDelay(pdMS_TO_TICKS(100));
						break;
					}

			}

	}

}


/*--------------------------------------
 * Initialisation Task
 * 1. Connects to ubidots MQTT broker
 * 2. Initialises temperature sensor
 * 3. Creates semaphores
 * 4. Creates temperature and RTC tasks
 * 5. Subscribes to LED_Control variable
 * 6. Task deletes itself
 ----------------------------------------*/
static void initTask(void * pvParameters) {
	uint32_t ret;
	printf("Starting Init Task\r\n");

	while(1) {
		HAL_GPIO_WritePin(LED2_GPIO_Port, LED2_Pin, GPIO_PIN_RESET);
		brokerConnect(&client);	//connect to WiFi access point and then to MQTT broker
		publishSemaphore = xSemaphoreCreateBinary();
		vQueueAddToRegistry(publishSemaphore, "Publish Semaphore");
		oneSecondSemaphore = xSemaphoreCreateBinary();
		vQueueAddToRegistry(oneSecondSemaphore, "RTC Semaphore");
		timerSemaphore = xSemaphoreCreateBinary();
		vQueueAddToRegistry(timerSemaphore, "Timer Semaphore");
		Publish_EventGroup = xEventGroupCreate();
		Button_EventGroup = xEventGroupCreate();
		xEventGroupSetBits(Button_EventGroup, buttonBit);
		dataQueue = xQueueCreate(5, sizeof(dataStruct_t));
		vQueueAddToRegistry(dataQueue, "Data Queue");

		autoReloadTimer = xTimerCreate("Auto Reload ", pdMS_TO_TICKS(4000), pdTRUE, 0, autoReloadTimerCallback);
		ledTimer = xTimerCreate("LED Reload ", pdMS_TO_TICKS(1000), pdTRUE, 0, ledTimerCallback);
		xTimerStart(autoReloadTimer, 0);

		__HAL_TIM_CLEAR_IT(&htim6, TIM_IT_UPDATE);
		HAL_NVIC_GetPendingIRQ(TIM6_DAC_IRQn);
		HAL_TIM_Base_Start_IT(&htim6);
		HAL_UART_Receive_IT(&huart1, &ch, 1);

		if(xTaskCreate(temperatureTask, "Temperature Task", 200, NULL, configMAX_PRIORITIES - 5, NULL) == pdTRUE) {
			printf("Temperature task created\n\r");
		}
		else {
			printf("Could not create temperature task\n\r");
		}
		if(xTaskCreate(humidityTask, "Humidity Task", 200, NULL, configMAX_PRIORITIES - 5, NULL) == pdTRUE) {
			printf("Humidity task created\n\r");
		}
		else {
			printf("Could not create humidity task\n\r");
		}
		if(xTaskCreate(RTC_Task, "RTC Task", 500, NULL, configMAX_PRIORITIES - 2, NULL) == pdTRUE) {
			printf("RTC task created\n\r");
		}
		else {
			printf("Could not create RTC task\n\r");
		}
		if(xTaskCreate(pressureTask, "Pressure Task", 200, NULL, configMAX_PRIORITIES - 4, NULL) == pdTRUE) {
			printf("Pressure task created\n\r");
		}
		else {
			printf("Could not create Pressure task\n\r");
		}
		if(xTaskCreate(accelerometerTask, "Accelerometer Task", 500, NULL, configMAX_PRIORITIES - 6, &accTaskHandle) == pdTRUE) {
			printf("Accelerometer task created\n\r");
		}
		else {
			printf("Could not create Accelerometer task\n\r");
		}
		if(xTaskCreate(displayTask, "Display Task", 500, NULL, configMAX_PRIORITIES - 3, NULL) == pdTRUE) {
			printf("Display task created\n\r");
		}
		else {
			printf("Could not create Display task\n\r");
		}


		//Subscribe to topics here
		//change the device name and variable name in the function call to match your Ubidots configuration
		ret = MQTTSubscribe(&client, "/v1.6/devices/rtosproject/ledonoff", QOS0, (subscribeMessageHandler));
		if (ret != MQSUCCESS) {
			printf("\n\rSubscribe failed: %ld\n\r", ret);
		}
		else {
			printf("\n\rSubscribed to topic \n\r");
			ret = MQTTYield(&client, 500);
		}


		//change the device name and variable name in the function call to match your Ubidots configuration
		ret = MQTTSubscribe(&client, "/v1.6/devices/rtosproject/ledslider", QOS0, (subscribeMessageHandler));
		if (ret != MQSUCCESS) {
			printf("\n\rSubscribe failed: %ld\n\r", ret);
		}
		else {
			printf("\n\rSubscribed to topic \n\r");
			ret = MQTTYield(&client, 500);
		}


		printf("Deleting Init Task\r\n\n");
		vTaskDelete(NULL);
	}
}

/*-----------------------------------------------
 * User application function
 * Creates Init task and starts ROS scheduler
-------------------------------------------------*/
void userApp() {
	printf("Starting user application\r\n\n");
	xTaskCreate(initTask, "Init Task", 2000, NULL, configMAX_PRIORITIES - 1, NULL);
	vTaskStartScheduler();

	while(1) {
	}
}

/*-------------------------------------------------
 * Function to establish connection to cloud server
 * 1. Connects to WiFi access point (AP)
 * 2. Gets date and time from network
 * 3. Connects to ubidots web server
 * 4. Connects to Ubidots MQTT broker
---------------------------------------------------*/
void brokerConnect(MQTTClient * client) {
	int32_t ret;
	//Network and MQTT variables
	device_config_t MQTT_Config;
	static unsigned char mqtt_send_buffer[MQTT_SEND_BUFFER_SIZE];
	static unsigned char mqtt_read_buffer[MQTT_READ_BUFFER_SIZE];
	net_ipaddr_t ipAddr;
	net_macaddr_t macAddr;

#ifdef USE_MBED_TLS
	conn_sec_t connection_security  = CONN_SEC_UNDEFINED;
	const char * device_cert  = NULL;
	const char * device_key   = NULL;
#endif


	//Initialise MQTT broker structure
	//Fill in this section with MQTT broker credentials from header file
	MQTT_Config.HostName = CloudBroker_HostName;
	MQTT_Config.HostPort = CloudBroker_Port;
	MQTT_Config.ConnSecurity = "0";	//plain TCP connection with no security
	MQTT_Config.MQUserName = CloudBroker_Username;
	MQTT_Config.MQUserPwd = CloudBroker_Password;
	MQTT_Config.MQClientId = CloudBroker_ClientID;

	//Initialise WiFi network
	if (net_init(&hnet, NET_IF, (wifi_net_if_init)) != NET_OK) {
		printf("\n\rError");
	}
	else {
		printf("\n\rOK");
	}
	HAL_Delay(500);

	printf("\n\rRetrieving the IP address.");

	if (net_get_ip_address(hnet, &ipAddr) != NET_OK) {
		printf("\n\rError 2");
	}
	else
	{
		switch(ipAddr.ipv) {
			case NET_IP_V4:
				printf("\n\rIP address: %d.%d.%d.%d\n\r", ipAddr.ip[12], ipAddr.ip[13], ipAddr.ip[14], ipAddr.ip[15]);
				break;
			case NET_IP_V6:
			default:
				printf("\n\rError 3");
		}
	}

	if (net_get_mac_address(hnet, &macAddr) == NET_OK) {
		printf("\n\rMac Address: %02x:%02x:%02x:%02x:%02x:%02x\r\n",
	               macAddr.mac[0], macAddr.mac[1], macAddr.mac[2], macAddr.mac[3], macAddr.mac[4], macAddr.mac[5]);
	}

	/*
	* Fetch the epoch time from st.com and use it to set the RTC time
	*/
	if (setRTCTimeDateFromNetwork(true) != TD_OK) {
		printf("Fail setting time\r\n");
	}
	else {
		printf("Time set, Starting RTC\r\n");
		//RTC started with a 1-second wake-up interrupt
		HAL_RTCEx_SetWakeUpTimer_IT(&hrtc, 2047, RTC_WAKEUPCLOCK_RTCCLK_DIV16);
	}

#ifdef USE_MBED_TLS
	printf("Connecting to MQTT Broker Server using TLS\r\n\n");
	//Create network socket
	//ret = net_sock_create(hnet, &socket, NET_PROTO_TCP);
	connection_security = CONN_SEC_SERVERAUTH;
	//ret = net_sock_create(hnet, &socket, (connection_security == CONN_SEC_NONE) ? NET_PROTO_TCP :NET_PROTO_TLS);
	ret = net_sock_create(hnet, &socket, NET_PROTO_TLS);
#else
	printf("Connecting to MQTT Broker Server\r\n\n");
	ret = net_sock_create(hnet, &socket, NET_PROTO_TCP);
#endif
	if (ret != NET_OK)
	{
		printf("\n\rCould not create the socket.\r\n");
		printf("Check MQTT broker configuration settings.\r\n");
		while(1);
	}
	else
	{
#ifdef USE_MBED_TLS
		//ret |= net_sock_setopt(socket, "sock_noblocking", NULL, 0);
        switch(connection_security)
        {
          case CONN_SEC_MUTUALAUTH:
            ret |= ((checkTLSRootCA() != 0) && (checkTLSDeviceConfig() != 0) )
              || (getTLSKeys(&ca_cert, &device_cert, &device_key) != 0);
            ret |= net_sock_setopt(socket, "tls_server_name", (void *) CloudBroker_HostName, strlen(CloudBroker_HostName) + 1);
            ret |= net_sock_setopt(socket, "tls_ca_certs",    (void *) ca_cert,                 strlen(ca_cert) + 1);
            ret |= net_sock_setopt(socket, "tls_dev_cert",    (void *) device_cert,             strlen(device_cert) + 1);
            ret |= net_sock_setopt(socket, "tls_dev_key",     (void *) device_key,              strlen(device_key) + 1);
            break;
          case CONN_SEC_SERVERNOAUTH:
            ret |= net_sock_setopt(socket, "tls_server_noverification", NULL, 0);
            ret |= (checkTLSRootCA() != 0)
              || (getTLSKeys(&ca_cert, NULL, NULL) != 0);
            ret |= net_sock_setopt(socket, "tls_server_name", (void *) CloudBroker_HostName, strlen(CloudBroker_HostName) + 1);
            ret |= net_sock_setopt(socket, "tls_ca_certs",    (void *) ca_cert,                 strlen(ca_cert) + 1);
              break;
          case CONN_SEC_SERVERAUTH:
            ret |= net_sock_setopt(socket, "tls_server_name", (void *) CloudBroker_HostName, strlen(CloudBroker_HostName) + 1);
            ret |= net_sock_setopt(socket, "tls_ca_certs",    (void *) ca_cert,                 strlen(ca_cert) + 1);
            break;
          case CONN_SEC_NONE:
            break;
          default:
            msg_error("Invalid connection security mode. - %d\n", connection_security);
        }
#endif
        ret |= net_sock_setopt(socket, "sock_noblocking", NULL, 0);
        if (ret != NET_OK)
		{
			printf("Could not retrieve the security connection settings and set the socket options.\n");
			while(1);
		}
		else {


			ret = net_sock_open(socket, MQTT_Config.HostName, atoi(CloudBroker_Port), 0);
			if (ret != NET_OK)
			{
				printf("\n\rCould not open the socket.");
				while(1);
			}
			else {
#ifdef USE_MBED_TLS
				printf("\r\nTLS connection established to MQTT Broker Server\r\n\n");
#else
				printf("\r\nConnection established to MQTT Broker Server\r\n\n");
#endif
			HAL_Delay(1000);
			}
		}


		network.my_socket = socket;
		network.mqttread = (network_rd);
		network.mqttwrite = (network_wr);

		MQTTClientInit(client, &network, MQTT_CMD_TIMEOUT, mqtt_send_buffer, MQTT_SEND_BUFFER_SIZE,
				mqtt_read_buffer, MQTT_READ_BUFFER_SIZE);

		/* MQTT connect */
		options.clientID.cstring = MQTT_Config.MQClientId;
		options.username.cstring = MQTT_Config.MQUserName;
		options.password.cstring = MQTT_Config.MQUserPwd;

		HAL_Delay(1000);

		printf("Connecting client to MQTT Broker\r\n\n");
		ret = MQTTConnect(client, &options);
		if (ret != 0)
		{
			printf("\n\rMQTTConnect() failed: %ld\n", ret);
			printf("Check MQTT client credential settings.\r\n");
			while(1);
		}
		else
		{
			printf("\n\rClient Connected to MQTT Broker\r\n");
			HAL_Delay(1000);
		}
		HAL_Delay(1000);
	}

}
